s1 = "    Zeenath fatima ,fatima ,fatima        "
s2 ="*"
print (len(s1))
print (s1.title())
print (s1.lower())
print(s1.upper())
print(s1.count("fatima"))       
print(s1.find("fatima"))
print(s1.index("fatima"))
print(s1.endswith("fatima"))
print(s1.isspace())
print(s1.islower())
print(s1.isupper())
print(s1.istitle())
print(s1.lstrip())
print(s1.rstrip())
print(s1.rstrip())
print(s1.strip())
print(s1.replace("e","*"))
print(s2.join(s1))
print(s1.partition("fatima"))
print (s1.split("a"))
